name: Fraud MLOps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GCP_PROJECT_ID: fraud-detection-mlops-503308
  GCP_REGION: asia-south2
  GAR_REPOSITORY: fraud-mlops
  IMAGE_NAME: fraud-api
  CLOUD_RUN_SERVICE: fraud-detection-api

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -v


  build-and-deploy:
    needs: test

    if: github.event_name == 'push' && vars.ENABLE_GCP_DEPLOY == 'true'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker \
          ${{ env.GCP_REGION }}-docker.pkg.dev \
          --quiet

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/amd64 \
          -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
          .

      - name: Push Docker image
        run: |
          docker push \
          ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          docker push \
          ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
          --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --region=${{ env.GCP_REGION }} \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --quiet

      - name: Production health check
        run: |
          SERVICE_URL=$(gcloud run services describe \
          ${{ env.CLOUD_RUN_SERVICE }} \
          --region=${{ env.GCP_REGION }} \
          --format='value(status.url)')

          echo "Production URL: $SERVICE_URL"

          curl --fail \
          --retry 10 \
          --retry-delay 5 \
          "$SERVICE_URL/health"
